### ISSUE TITLE
Design Contact page

### ISSUE THREAD

**Issue by ShivanshiDas** [CSAllenISD/2023-ISP-ShelterSafe#18]
A contact page is needed to ensure that users can report bugs and reach our support team if needed. The contact page is needed for the betterment and longevity of the overall product.

**Comment by Zoe-yau** [comment]
That's a great idea! We definitely need away for the users to contact us and reach out to us.

**Comment by onikh** [comment]
That's something I didn't think about. It's a great idea, our product can only benefit from it!

**Comment by omerert** [comment]
It would be a good idea to get reports for bugs

**Comment by Zoe-yau** [comment]
Should we create a contact email and make a list of numbers that people can easily call (like hotlines)?

**Comment by kripatailor** [comment]
I think creating an email for the app is a great idea, but we also have to make sure that whoever has access to the email checks it frequently

**Comment by Zoe-yau** [comment]
Completed we added this into an about us page
