### ISSUE TITLE
Decide on color-scheme

### ISSUE THREAD

**Issue by ShivanshiDas** [CSAllenISD/2023-ISP-ShelterSafe#19]
We are looking for a color-scheme that is both pleasing and not overwhelming at the same time. We want the user interface to look appealing without taking away from readability.

**Comment by sophiaptran** [comment]
I agree! The color scheme should be something appealing to the eye.

**Comment by onikh** [comment]
I feel like blue is a good idea: the Red Cross has an app based around disasters that already use red, and blue is a generally soothing color with tons of versatility.

**Comment by sophiaptran** [comment]
Yes, blue is a good color and we should keep this color-scheme since most of our prototype logos fit with this color-scheme.

**Comment by Zoe-yau** [comment]
Whatever color-scheme we decide on they should be the color of our logos.

**Comment by omerert** [comment]
I agree that the color scheme should match with our logo

**Comment by kripatailor** [comment]
Completed! We chose neutral colors
