### ISSUE TITLE
Discuss logo designs

### ISSUE THREAD

**Issue by ShivanshiDas** [CSAllenISD/2023-ISP-ShelterSafe#20]

**Comment by SrisaivikasMunagala** [comment]
Having a good logo will attract more users.👍

**Comment by sophiaptran** [comment]
I agree, a good logo will defiantly attract users. We should vote as soon as possible so we can perfect the logo.

**Comment by kripatailor** [comment]
I agree, choosing a logo that would best fit our color scheme would be the best idea, but I sill think we should vote because they both look great!

**Comment by Zoe-yau** [comment]
Completed! [](url)
