### ISSUE TITLE
Design home page of the app

### ISSUE THREAD

**Issue by kripatailor** [CSAllenISD/2023-ISP-ShelterSafe#21]

**Comment by Zoe-yau** [comment]
I agree! I think the home page should be something attention grabbing and informative.

**Comment by sophiaptran** [comment]
This is a great idea and essential for creating our app.

**Comment by omerert** [comment]
A home page would be a good idea

**Comment by kripatailor** [comment]
I think that it is a great idea and it would be a good idea to match it with out color scheme

**Comment by sophiaptran** [comment]
A simple home page will be a good idea to keep everything organized and look presentable.

**Comment by Zoe-yau** [comment]
We could combine the about us page with the home page.

**Comment by kripatailor** [comment]
Completed! We made a login screen instead
