### ISSUE TITLE
discuss app store implementation

### ISSUE THREAD

**Issue by jishnud17** [CSAllenISD/2023-ISP-ShelterSafe#22]

**Comment by SrisaivikasMunagala** [comment]
Yes. This is important as we need to figure out how we will publish to the App Store.

**Comment by PranavKrishnan05** [comment]
This should be in Todo because we dont have a final product to put in the app store yet

**Comment by omerert** [comment]
We will need this soon to run tests and detect any bugs from a user's view.

**Comment by sophiaptran** [comment]
Yes I agree! This is something we should start researching and begin working on.

**Comment by Zoe-yau** [comment]
We need to discuss whether we will be adding a price to the app or a certain membership status. However, I am assuming since we want this to be accessible to all we want it to be free. Will this app be considered a non-profit then?
