### ISSUE TITLE
ensure each programmer has a .netrc file in their home directory

### ISSUE THREAD

**Issue by shivangi316** [CSAllenISD/2023-ISP-ShelterSafe#30]
A .netrc file contains login information for administrators on the app so that no random person can edit and display misinformation. It is necessary to have this file so have writing access to the data and the app.

**Comment by PranavKrishnan05** [comment]
This is required but at this moment we still arent able to ues packages after creating the netrc file so we must fix that issue aswell

**Comment by Zoe-yau** [comment]
We should verify with everyone, but all of us in 6th period have created a .netrc file and have xcode running on our personal macs.

**Comment by kripatailor** [comment]
I think that it would be a great idea to make sure that everyone has that file because that could be the main reason some of us are having issues.

**Comment by sophiaptran** [comment]
Yes I agree, a .netrc file is required, which means it is vital for everyone to have one and to be able to access xcode.

**Comment by omerert** [comment]
A .netrc will be important to access xcode
