### ISSUE TITLE
Fix Xcode on School Computers

### ISSUE THREAD

**Issue by PranavKrishnan05** [CSAllenISD/2023-ISP-ShelterSafe#34]

**Comment by omerert** [comment]
I agree

**Comment by kripatailor** [comment]
I think that is a good idea and it would be best to do that as soon as we can

**Comment by ShivanshiDas** [comment]
If we don't find a work around by out next team meeting, it might be beneficial to discuss this matter with Mr. Ben and see if IT can do anything about this.

**Comment by PranavKrishnan05** [comment]
This still an issue we must figure out a way to contact IT, Ill discuss this with our team lead

**Comment by onikh** [comment]
3rd period has this problem solved. I know 6th period mostly has their own personal macs, but if you guys ever need to use the school ones, just ask Mr. Ben and he can get IT to solve the issue in minutes!

**Comment by Zoe-yau** [comment]
Since this problem is more of an administration/ IT problem, I think Onikhs suggestion is a great idea! It is the best solution to go into Mr. Ben's class and ask for him to help.
