### ISSUE TITLE
Create a GANTT Chart

### ISSUE THREAD

**Issue by omerert** [CSAllenISD/2023-ISP-ShelterSafe#37]
We should create a GANTT chart to track our current progress in our project.

**Comment by kripatailor** [comment]
Yes we should get to that a soon as we can.

**Comment by ShivanshiDas** [comment]
I believe Onik and Pranav had already created a GANTT chart in their initial proposal of ShelterSafe, but I feel that we would benefit from revising it to better suit our team and accommodate for the changes that have been made since the initial proposal.

**Comment by onikh** [comment]
You're completely right Shivanshi. I'll close this issue, but open another one to revise the existing Gannt Chart.
