### ISSUE TITLE
Design an about us page

### ISSUE THREAD

**Issue by Zoe-yau** [CSAllenISD/2023-ISP-ShelterSafe#40]

**Comment by SrisaivikasMunagala** [comment]
This is vital for users to contact us.

**Comment by PranavKrishnan05** [comment]
We need to split up the roles internaly between the software devs and make sure someone is working on this so we can get good feedback

**Comment by onikh** [comment]
I like this idea! We could combine it into a page with Sophia's frequently asked questions idea and Shivanshi's contact us idea.

**Comment by omerert** [comment]
I agree that we should combine this page with the faq page.

**Comment by sophiaptran** [comment]
An about us page is a great idea. I think we should keep this separate, and combine just the faq page with the contact page.

**Comment by kripatailor** [comment]
That is a great idea, and I think we should combine the about us page and contact page because it would be easy for the users to know everything about the app on one page and not have to got to different pages.

**Comment by kripatailor** [comment]
Completed!
