### ISSUE TITLE
Decide on a theme

### ISSUE THREAD

**Issue by Zoe-yau** [CSAllenISD/2023-ISP-ShelterSafe#41]

**Comment by SrisaivikasMunagala** [comment]
I agree. We need to pick a color palette.

**Comment by onikh** [comment]
Suggestion: earth colors with mostly shades of brown? (beige, tan, coffee, etc.)
I think it'd match our logo/icons/art aesthetic perfectly.

**Comment by sophiaptran** [comment]
I agree with Onik's idea of using earth tones. We should also include a pop of color to catch people's eyes, such as blues since we have already been incorporating some blue tones.

**Comment by Zoe-yau** [comment]
I actually disagree. As much as I love earth tones, I think it we should stick with a blue color theme. Blue feels more natural and is a theme that fits well with our app idea.

**Comment by omerert** [comment]
The theme should be similar to the colors of our logo

**Comment by kripatailor** [comment]
Completed - We decided on a neutral color theme
