### ISSUE TITLE
Pakages not working on team member's personal macs

### ISSUE THREAD

**Issue by PranavKrishnan05** [CSAllenISD/2023-ISP-ShelterSafe#46]
The packages do not load when pulling from git hub

![Image](https://user-images.githubusercontent.com/88994955/218175342-d367636c-8167-4b91-987f-869a2c092ca9.png)

**Comment by onikh** [comment]
Some of our other group members had this problem: it was always related to the .netrc file with the API key. Rather than placing the content of the file like the documentation shows, try putting it all on one line. If it keeps erroring, let me know and I'd be glad to help!

**Comment by kripatailor** [comment]
I edited the .netrc after reading this and made it to one line, thank you for helping!
