### ISSUE TITLE
Add Point Annotation Image to Assets

### ISSUE THREAD

**Issue by SrisaivikasMunagala** [CSAllenISD/2023-ISP-ShelterSafe#55]
Add Red Point Annotation to the Assets folder in xcodeproj to display shelter points.

**Comment by PranavKrishnan05** [comment]
we have completed that with the latest commit to Mapkit https://github.com/CSAllenISD/2023-ISP-ShelterSafe/commit/6fb85af9b29de98390153ad0288786e83a0bd8ce 😄
