### ISSUE TITLE
point annotations and feature annotations

### ISSUE THREAD

**Issue by shivangi316** [CSAllenISD/2023-ISP-ShelterSafe#59]
we should convert point annotations to feature annotations, create class for shelters and make sure they can be converted to json objects

**Comment by PranavKrishnan05** [comment]
We have fully implemented the annotations with popups and added a list view for all of these locations. I will open another issue about connecting our new LocationDataService to our json file

https://github.com/CSAllenISD/2023-ISP-ShelterSafe/commit/6fb85af9b29de98390153ad0288786e83a0bd8ce
