### ISSUE TITLE
Add Contacts to contact spreadsheet

### ISSUE THREAD

**Issue by Zoe-yau** [CSAllenISD/2023-ISP-ShelterSafe#79]

**Comment by Zoe-yau** [comment]
We have added contacts and addresses for multiple states across the United States.

**Comment by Zoe-yau** [comment]
[](https://docs.google.com/spreadsheets/d/17WtEtBKeE3EtwKiYMN123m5w5Cg6z9qxT-KTuwEjs3U/edit?usp=sharing)

**Comment by kripatailor** [comment]
We have many places in this list from different places and we have all the information that we thought could be useful  when adding to the app
